version: '3'

services:
  rabbit:
    image: rabbitmq:3.6-management
    hostname: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123123
    volumes:
      - ./data:/var/lib/rabbitmq
  rabbit_exporter:
    image: kbudde/rabbitmq-exporter:v1.0.0-RC7.1
    restart: always
    ports:
      - "9419:9419"
    environment:
      - RABBIT_URL=http://rabbit:15672
      - RABBIT_USER=root
      - RABBIT_PASSWORD=123123
